/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Actions.Entradas;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.*;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author marce
 */
public class HomeListado extends javax.swing.JFrame {

    /**
     * Creates new form HomeListado
     */
    public HomeListado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelRegistroEquipo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtBuscarEquipo = new javax.swing.JTextField();
        btnBuscarEquipo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListadoEquipos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sistema de Control equipos SV - CLARO");
        setPreferredSize(new java.awt.Dimension(1106, 572));

        jPanelRegistroEquipo.setBackground(new java.awt.Color(255, 255, 255));
        jPanelRegistroEquipo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 5));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("LISTADO DE EQUIPOS");

        jLabel12.setText("Buscar por:");

        txtBuscarEquipo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnBuscarEquipo.setText("BUSCAR");
        btnBuscarEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarEquipoActionPerformed(evt);
            }
        });

        tblListadoEquipos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblListadoEquipos);

        javax.swing.GroupLayout jPanelRegistroEquipoLayout = new javax.swing.GroupLayout(jPanelRegistroEquipo);
        jPanelRegistroEquipo.setLayout(jPanelRegistroEquipoLayout);
        jPanelRegistroEquipoLayout.setHorizontalGroup(
            jPanelRegistroEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegistroEquipoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelRegistroEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelRegistroEquipoLayout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscarEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscarEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(460, Short.MAX_VALUE))
            .addGroup(jPanelRegistroEquipoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanelRegistroEquipoLayout.setVerticalGroup(
            jPanelRegistroEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegistroEquipoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRegistroEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtBuscarEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarEquipo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1106, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelRegistroEquipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 575, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelRegistroEquipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarEquipoActionPerformed
        // TODO add your handling code here:

        String ParametroBusqueda = txtBuscarEquipo.getText();
        
        try 
        {
            //Acceso al registro de PC en base de datos
            CrearTabla(ParametroBusqueda);
        } 
        catch (SQLException ex) 
        {
            Logger.getLogger(HomeListado.class.getName()).log(Level.SEVERE, null, ex);
        }
                
    }//GEN-LAST:event_btnBuscarEquipoActionPerformed

    public void CrearTabla(String ParametroBusqueda) throws SQLException
    {
     
        //Crear tabla
        DefaultTableModel tabla = new DefaultTableModel();
        tabla.addColumn("ID");
        tabla.addColumn("MARCA");
        tabla.addColumn("MODELO");
        tabla.addColumn("AÑO");
        tabla.addColumn("ESTATUS");
        tabla.addColumn("REGISTRO");
        tabla.addColumn("GARANTIA");
        tabla.addColumn("ESPECIFICACIONES");
        tabla.addColumn("CONDICIONES");
        tabla.addColumn("WINDOWS");
        tabla.addColumn("OFFICE");
        tabla.addColumn("DETALLES");
        tabla.addColumn("OPCION");
        tblListadoEquipos.setModel(tabla);
        
        //Informacion con filtro
        Entradas entra = new Entradas();
        ArrayList ListadoEquiposRecibe = entra.BuscarRegistroPC(ParametroBusqueda);
        Integer count = ListadoEquiposRecibe.size();
        System.out.println("The Length of ListadoEquiposRecibe-ArrayList is : " + count);
        
        String []fila = null;

        Integer i;
        /*for (i = 0; i < count; i++) 
        {
                JOptionPane.showMessageDialog(null, " CONTADOR" +  i);
                fila = (String[]) ListadoEquiposRecibe.get(i);
                
                for(int j=0;j<12;j++)
                {
                    System.out.println(fila[j]);
                }
                
                tabla.addRow(fila);
                
                
                //filastring = Arrays.toString(fila);
                //System.out.println("The Length of ListadoEquiposRecibe-ArrayList is 2 : " + Arrays.toString(fila));
        }*/
        //tblListadoEquipos.setModel(tabla);
        
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeListado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeListado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeListado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeListado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeListado().setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarEquipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JPanel jPanelRegistroEquipo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblListadoEquipos;
    private javax.swing.JTextField txtBuscarEquipo;
    // End of variables declaration//GEN-END:variables
}
