/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;


import Actions.Complementos;
import Actions.Entradas;
import Network.Conexion;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.JFrame;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author marce
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() 
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelRegistroEquipo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtModeloRegistro = new javax.swing.JTextField();
        cmbEstatusRegistro = new javax.swing.JComboBox<>();
        cmbAniosRegistro = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaCondicionesRegistro = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaEspecificacionesRegistro = new javax.swing.JTextArea();
        dtFechaGarantiaRegistro = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        cmbVersionWindowsRegistro = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        cmbVersionOfficeRegistro = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAreaDettaleVersionesRegistro = new javax.swing.JTextArea();
        tbnIngresarRegistro = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtMarcaRegistro = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sistema de Control equipos SV - CLARO");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanelRegistroEquipo.setBackground(new java.awt.Color(255, 255, 255));
        jPanelRegistroEquipo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 5));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("REGISTRO DE EQUIPOS");

        jLabel2.setText("Modelo:");

        jLabel3.setText("Estatus:");

        jLabel4.setText("Año:");

        jLabel6.setText("Fecha garantia:");

        jLabel7.setText("Condiciones:");

        cmbEstatusRegistro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NUEVO", "USADO", "REPARADO", "DE BAJA", "ACTIVO", "INACTIVO", "SALIDA" }));

        cmbAniosRegistro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035", "2036", "2037", "2038", "2039", "2040", "2041", "2042", "2043", "2044", "2045", "2046", "2047", "2048", "2049", "2050", "2051", "2052", "2053", "2054", "2055", "2056", "2057", "2058", "2059", "2060" }));
        cmbAniosRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAniosRegistroActionPerformed(evt);
            }
        });

        txtAreaCondicionesRegistro.setColumns(20);
        txtAreaCondicionesRegistro.setRows(5);
        txtAreaCondicionesRegistro.setText("Sin comentarios");
        jScrollPane1.setViewportView(txtAreaCondicionesRegistro);

        jLabel8.setText("Especificaciones:");

        txtAreaEspecificacionesRegistro.setColumns(20);
        txtAreaEspecificacionesRegistro.setRows(5);
        txtAreaEspecificacionesRegistro.setText("Sin comentarios");
        jScrollPane2.setViewportView(txtAreaEspecificacionesRegistro);

        jLabel9.setText("Version Windows:");

        cmbVersionWindowsRegistro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "WINDOWS 7", "WINDOWS 8", "WINDOWS 10", "WINDOWS 11", "OTRO" }));

        jLabel10.setText("Version Office:");

        cmbVersionOfficeRegistro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "OFFICE 365", "OFFICE 2016", "OTRO" }));

        jLabel11.setText("Detalle de versiones Windows/Office:");

        txtAreaDettaleVersionesRegistro.setColumns(20);
        txtAreaDettaleVersionesRegistro.setRows(5);
        txtAreaDettaleVersionesRegistro.setText("Sin comentarios");
        jScrollPane3.setViewportView(txtAreaDettaleVersionesRegistro);

        tbnIngresarRegistro.setText("INGRESAR REGISTRO");
        tbnIngresarRegistro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbnIngresarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbnIngresarRegistroActionPerformed(evt);
            }
        });

        jLabel12.setText("Marca:");

        javax.swing.GroupLayout jPanelRegistroEquipoLayout = new javax.swing.GroupLayout(jPanelRegistroEquipo);
        jPanelRegistroEquipo.setLayout(jPanelRegistroEquipoLayout);
        jPanelRegistroEquipoLayout.setHorizontalGroup(
            jPanelRegistroEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegistroEquipoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelRegistroEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRegistroEquipoLayout.createSequentialGroup()
                        .addGroup(jPanelRegistroEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelRegistroEquipoLayout.createSequentialGroup()
                                .addGroup(jPanelRegistroEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelRegistroEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtModeloRegistro)
                                    .addComponent(cmbEstatusRegistro, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmbAniosRegistro, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(dtFechaGarantiaRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
                                    .addComponent(txtMarcaRegistro)))
                            .addGroup(jPanelRegistroEquipoLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(jPanelRegistroEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanelRegistroEquipoLayout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanelRegistroEquipoLayout.createSequentialGroup()
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(tbnIngresarRegistro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanelRegistroEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelRegistroEquipoLayout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(148, Short.MAX_VALUE))
                            .addGroup(jPanelRegistroEquipoLayout.createSequentialGroup()
                                .addGroup(jPanelRegistroEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelRegistroEquipoLayout.createSequentialGroup()
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cmbVersionOfficeRegistro, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanelRegistroEquipoLayout.createSequentialGroup()
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cmbVersionWindowsRegistro, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(18, 18, 18))
                            .addComponent(jScrollPane3)))
                    .addGroup(jPanelRegistroEquipoLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanelRegistroEquipoLayout.setVerticalGroup(
            jPanelRegistroEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegistroEquipoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRegistroEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtMarcaRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(cmbVersionWindowsRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanelRegistroEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtModeloRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbVersionOfficeRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelRegistroEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbAniosRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel11))
                .addGroup(jPanelRegistroEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRegistroEquipoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelRegistroEquipoLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanelRegistroEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbEstatusRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(27, 27, 27)
                        .addGroup(jPanelRegistroEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dtFechaGarantiaRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelRegistroEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanelRegistroEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(tbnIngresarRegistro)
                .addGap(74, 74, 74))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1106, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelRegistroEquipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 572, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelRegistroEquipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbAniosRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAniosRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbAniosRegistroActionPerformed

    //Boton de registro de informacion PC
    private void tbnIngresarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbnIngresarRegistroActionPerformed
                
        //Instancias        
        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd 00:00:00");        
        Complementos comple = new Complementos();
        Entradas entra = new Entradas();
        Date sis = new Date();     
        SimpleDateFormat formatter_sis = new SimpleDateFormat("yyyy-MM-dd hh:mm:ss");
                
        //Variables
        String Marca = "";
        String Modelo = "";
        String Anio = "";
        String Status = "";
        String FechaRegistro = "";
        Date FechaGarantia;
        String FechaGarantiaString = "";
        String Especificaciones = "";
        String Condiciones = "";
        String VersionWindows = "";
        String VersionOffice = "";
        String DetallesVersiones = "";
        Boolean FlagMarca = false;
        Boolean FlagModelo = false;
        Boolean FlagFechaGarantia = false;
        Boolean FlagEntrada = false;   
        String FechaSistema = "";
        
        FechaSistema = formatter_sis.format(sis);

        //Registro de PC
        Marca  = txtMarcaRegistro.getText();
        Modelo = txtModeloRegistro.getText();
        Anio = (String) cmbAniosRegistro.getSelectedItem();
        Status = (String) cmbEstatusRegistro.getSelectedItem();   
        FechaRegistro = FechaSistema;      
        FechaGarantia = dtFechaGarantiaRegistro.getDate();
        Especificaciones = txtAreaEspecificacionesRegistro.getText();
        Condiciones = txtAreaCondicionesRegistro.getText();
        VersionWindows = (String) cmbVersionWindowsRegistro.getSelectedItem();
        VersionOffice = (String) cmbVersionOfficeRegistro.getSelectedItem();
        DetallesVersiones = txtAreaDettaleVersionesRegistro.getText();
            
        //Validacion de valores en registro de PC            
        FlagMarca = comple.StringEsNulo(Marca,"Marca");//Marca
        FlagModelo = comple.StringEsNulo(Modelo,"Modelo");//Modelo
        FlagFechaGarantia = comple.DateEsNulo(FechaGarantia,"Fecha Garantia");//FechaGarantia
        if(FlagFechaGarantia == true)
        {
            FechaGarantiaString = formatter.format(FechaGarantia);   
        }
            
        try 
        {
            //Ingreso de registro de PC en base de datos
            entra.InsertRegistroPC(Marca, Modelo, Anio, Status, FechaRegistro,
                        FechaGarantiaString, Especificaciones, Condiciones, VersionWindows,
                        VersionOffice,DetallesVersiones );
        } 
        catch (SQLException ex) 
        {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_tbnIngresarRegistroActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) 
    {   
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }*/
        //</editor-fold>
            
        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() 
        {
            public void run() 
            {
                new Home().setVisible(true);
            }
        });*/
    }
     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbAniosRegistro;
    private javax.swing.JComboBox<String> cmbEstatusRegistro;
    private javax.swing.JComboBox<String> cmbVersionOfficeRegistro;
    private javax.swing.JComboBox<String> cmbVersionWindowsRegistro;
    private com.toedter.calendar.JDateChooser dtFechaGarantiaRegistro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanelRegistroEquipo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton tbnIngresarRegistro;
    private javax.swing.JTextArea txtAreaCondicionesRegistro;
    private javax.swing.JTextArea txtAreaDettaleVersionesRegistro;
    private javax.swing.JTextArea txtAreaEspecificacionesRegistro;
    private javax.swing.JTextField txtMarcaRegistro;
    private javax.swing.JTextField txtModeloRegistro;
    // End of variables declaration//GEN-END:variables
}
